apiVersion: v1
kind: Pod
metadata:
  name: p5-dlc-inventory
  namespace: gpu-communication-lab
  labels:
    app: p5-dlc-inventory
spec:
  restartPolicy: Never
  nodeSelector:
    workload: p5-efa-lab
  tolerations:
    - key: workload
      operator: Equal
      value: p5-efa-lab
      effect: NoSchedule
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  containers:
    - name: inventory
      image: public.ecr.aws/deep-learning-containers/pytorch-training:2.9.0-gpu-py312-cu130-ubuntu22.04-ec2@sha256:c5af70b4143d7b1878567cc198c5a7961aff15e8c59fec35c2fb3cbd097cddcd
      imagePullPolicy: IfNotPresent
      command: ["bash", "-lc", "sleep infinity"]
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
          nvidia.com/gpu: "1"
          vpc.amazonaws.com/efa: "1"
        limits:
          nvidia.com/gpu: "1"
          vpc.amazonaws.com/efa: "1"
